### ISSUE TITLE
LIBUSB_ERROR_TIMEOUT

### ISSUE THREAD

**Issue by Mariobit5** [dylwedma11748/JTegraNX#16]
I want to hack my switch(like everybody who install this software) and when I want to inject payload JTegraNX say that:

Creating RCM payload
Failed to read device ID
Error code: LIBUSB_ERROR_TIMEOUT
Sent 0 out of 31 target blocks
Failed to send payload to device

and the first time I try after put my switch in rcm mode it's

Creating RCM payload
Device ID: 0082020F0000000040F66C64212101D0
Sending payload to device
Sent 16 out of 31 target blocks
Failed to send payload to device

**Comment by dylwedma11748** [comment]
You failed to give me enough information as to why this is happening, but my best guess is it's a bad USB cable and/or port.
