### ISSUE TITLE
Can't launch with OpenJDK 16.0.1

### ISSUE THREAD

**Issue by alalloush** [dylwedma11748/JTegraNX#2]
Windows 10 20H2
OpenJDK 16.0.1

When running the jar via `java -jar JTegraNX.jar`, 
I get the error
`Error: Could not find or load main class ui.fx.JTegraNX
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application`

I'm not sure if the issue is from my end, but it might be possible that JavaFX isn't packaged properly.

**Comment by dylwedma11748** [comment]
Did some research, and it looks like from JDK 11, JavaFX is no longer included with the JDK, it's now a separate dependency. I don't know if this applies to OpenJDK 16, but I have a feeling it might. Try building JTegraNX from source using OpenJDK 16 and add JavaFX to the external dependencies.

**Comment by aihooo444** [comment]
go to command promt and type
java -jar myfile.jar
[JTegraNX.txt](https://github.com/dylwedma11748/JTegraNX/files/6633761/JTegraNX.txt)
or use this just change .txt to .bat and put in same folder as your jar file

**Comment by dylwedma11748** [comment]
@aihooo444 If you read the first comment for the issue you can see that he already tried that.

**Comment by dylwedma11748** [comment]
No responses, issue closed.

**Comment by dylwedma11748** [comment]
Ok, so instead of just closing this and ignoring it, I've decided to re-open this issue and get JavaFX packaged properly and hopefully get it done right to maximize compatibility. It will take some time and lots of testing on different JDK versions.

**Comment by dylwedma11748** [comment]
JTegraNX v1.6.8 properly packages JavaFX to fix this issue, closing.
