### ISSUE TITLE
[SUGGESTION] Support MacOS

### ISSUE THREAD

**Issue by PoloNX** [dylwedma11748/JTegraNX#3]
I friend, I see your problem with macOS on logic-sunrise.com, if you want I can help you I have a Mac and I can program in C++.
If you want talk with me on discord add me : PoloNX#9999

**Comment by dylwedma11748** [comment]
It says that your discord profile isn't accepting friend requests and that you'll have to add me, my username and tag is 7thousandnumbers#2314

**Comment by dylwedma11748** [comment]
JTegraNX v1.6.7 adds Mac OS X support. Closing.
